"""empty message

Revision ID: 6fc3e23229c4
Revises: 5aa265a662ee
Create Date: 2021-05-28 20:20:55.418668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fc3e23229c4'
down_revision = '5aa265a662ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'face_access')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('face_access', sa.BOOLEAN(), nullable=False))
    # ### end Alembic commands ###
