"""empty message

Revision ID: 85c163f37c46
Revises: 6fc3e23229c4
Create Date: 2021-05-28 20:21:53.518555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85c163f37c46'
down_revision = '6fc3e23229c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('face_access', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'face_access')
    # ### end Alembic commands ###
